name: TESTS

on: [pull_request]

jobs:
  test-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Bats
      run: ./scripts/install_bats.sh
    - name: Install dependencies
      run: npm i
    - name: Run tests
      run: npm t
  
  test-on-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Bats
      run: ./scripts/install_bats.sh
    - name: Install dependencies
      run: npm i
    - name: Run tests
      run: npm t
